Make run and push to overleaf compatible with multiple run files

diff --git a/.github/workflows/test_run_push_to_overleaf.yml b/.github/workflows/test_run_push_to_overleaf.yml
--- a/.github/workflows/test_run_push_to_overleaf.yml
+++ b/.github/workflows/test_run_push_to_overleaf.yml
@@ -40,6 +40,13 @@ jobs:
           python3 labproject/run.py
           cd ..
           cp labproject/plots/* overleaf/figures/
+     - name: Check for Errors
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "One or more scripts failed."
+            exit 1
+          fi
+
       - name: Commit and push changes to Overleaf
         run: |
             cd ${{ github.workspace }}
